### ISSUE TITLE
[1.18.2] Ender Dragon doesn't scale with Nullscape

### ISSUE THREAD

**Issue by Aarods** [Insane96/ProgressiveBosses#156] opened 2024-02-22 22:08 UTC
- Minecraft: 1.18.2
 - Forge: 40.2.17
 - Progressive Bosses: 3.6.8
 - InsaneLib: 1.5.3

* When summoning the Ender Dragon in the End, with Nullscape Installed (Mod Version: 1.1.4), the dragon does not obtain or execute any ability from this mod, even reviving it doesn't work.

* (No relevant info in the logs from what I see)

* Progressive Bosses + InsaneLib + Nullscape (Last Version of the Mod)

**Comment by Insane96** [comment] 2024-02-22 22:15
Are you using the datapack or the mod?

**Comment by Insane96** [comment] 2024-02-22 22:15
Possible duplicate of https://github.com/Insane96/ProgressiveBosses/issues/151

**Comment by Aarods** [comment] 2024-02-23 03:32
(Using Mod version) I think is the same issue. From what I see, It also happens in 1.19.

- Testing it only with Nullscape and Progressive Bosses, the problem is still occurring. 
- There is a version of Nullscape in datapack format, but is deprecated and there are more issues than the new one.

**Comment by Insane96** [comment] 2024-04-14 06:57
Older versions of Nullscape seem to be broken.

**Closed as not planned by Insane96** 2024-04-14 06:57 UTC
Labels: bug, needs more infos, other mod issue
