### ISSUE TITLE
Cannot run on Arclight

### ISSUE THREAD

**Issue by nainiu233** [Insane96/ProgressiveBosses#87] opened 2021-07-06 10:38 UTC
### serverlog
https://paste.ubuntu.com/p/8WJNfpF3FX/

### OneDrive
https://1drv.ms/u/s!Al_-L17sT3U9hfMaNrIaq13BEBt5-g?e=H8hxpc

https://github.com/IzzelAliz/Arclight/issues/316

**Comment by Insane96** [comment] 2021-07-06 10:41
I don't know what is Arclight, but I might know the cause. I will try to release a fix soon.

**Comment by Insane96** [comment] 2021-07-06 19:45
Hopefully fixed in Beta 3.1.2

**Comment by nainiu233** [comment] 2021-07-07 03:44
There are still problems with beta 3.1.2

https://paste.ubuntu.com/p/RXHBxCZ5WD/

**Comment by Insane96** [comment] 2021-07-07 05:24
Then I don't know what to do. The mod works properly on normal Forge.

**Comment by nainiu233** [comment] 2021-07-07 05:53
More information
2.2.0 available 
crash after upgrade

Arclight:This is the problem with their mixin 

OneDrive Has been updated

**Comment by Insane96** [comment] 2021-07-07 06:15
This doesn't help.

**Comment by qyl27** [comment] 2021-08-08 05:07
Same problem, Arclight is a forge + bukkit server (It using mixin to impl).
https://github.com/IzzelAliz/Arclight/tree/1.16

After I review the code, Maybe you should not override the method, but use mixin?
(I will take a test.)

**Comment by Insane96** [comment] 2021-08-08 06:44
Gonna make some tests, but what does the https://github.com/IzzelAliz/Arclight/blob/1.16/arclight-common/src/main/java/io/izzel/arclight/common/mixin/core/entity/projectile/ShulkerBulletEntityMixin.java#L38 Arclight's Mixin do with this method?

**Comment by qyl27** [comment] 2021-08-08 06:46
Yes, it used it for passing the cause to Bukkit.

**Comment by qyl27** [comment] 2021-08-08 06:53
Does the onBulletEntityHit in MinionFeature have another caller?
(https://github.com/Insane96/ProgressiveBosses/blob/1.16/src/main/java/insane96mcp/progressivebosses/module/dragon/feature/MinionFeature.java#L256)

**Closed as completed** 2021-08-08 07:00 UTC
Labels: bug, help wanted

**Comment by Insane96** [comment] 2021-08-08 07:01
Please test 3.3.2 (will be up in about 10 minutes) and check if the bug is fixed.

**Comment by qyl27** [comment] 2021-08-08 07:19
Seems it loaded successfully! Thank you.

**Comment by Insane96** [comment] 2021-08-08 08:47
Nice
